name: dlog

description: "DE Logistics"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #ios
  cupertino_icons: ^1.0.6
  #otp
  pinput: ^3.0.1
  #state management
  flutter_bloc: ^8.1.5
  #navigation
  go_router: ^14.1.1
  #network
  retrofit: ^4.1.0
  dio: ^5.4.0
  #logger
  pretty_dio_logger: ^1.3.1
  logger: ^2.3.0
  #storage
  shared_preferences: ^2.2.3
  #device info
  device_info_plus: ^10.1.0
  #formater
  intl: ^0.19.0
  #di
  get_it: ^7.7.0
  #localization
  flutter_localization: ^0.2.0
  #image
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/graphic/
    - assets/images/logo/
    - assets/images/icons/Arrows-chevron/
    - assets/images/icons/comercial/
    - assets/images/icons/documents/
    - assets/images/icons/general/
    - assets/images/icons/hicon/Bold/
    - assets/images/icons/hicon/Linear/
<<<<<<< HEAD
    - assets/images/icons/hicon/Outline/
    - assets/images/icons/iconex/Light/
    - assets/images/icons/interface_essential/

=======
    - assets/images/icons/hicon/Bold/
    - assets/images/icons/hicon/Outline/
    - assets/images/icons/iconex/Light/
    - assets/images/icons/interface_essential/
    - assets/images/icons/language/
    - assets/images/graphic/
    - assets/images/logo/
    - assets/images/sample/
>>>>>>> dev-ye
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700



