name: dlog

description: "DE Logistics"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #ios
  cupertino_icons: ^1.0.6
  #state management
  flutter_bloc: ^8.1.5
  #navigation
  go_router: ^14.1.0
  #network
  retrofit: ^4.1.0
  dio: ^5.4.0
  #logger
  pretty_dio_logger: ^1.3.1
  logger: ^2.3.0
  #storage
  shared_preferences: ^2.2.3
  #device info
  device_info_plus: ^10.1.0
  #formater
  intl: ^0.18.1
  #di
  get_it: ^7.7.0
  #localization
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700



